import Foundation

enum MonthGroupingTimeZoneCatalog {
    static let primaryIdentifiers: [String] = rawPrimaryIdentifiers
        .split(separator: "\n")
        .map(String.init)

    static func selectableIdentifiers(adding extras: [String?]) -> [String] {
        var seen = Set<String>()
        var result: [String] = []
        for identifier in primaryIdentifiers + extras.compactMap({ $0 }) {
            guard !identifier.isEmpty,
                  !seen.contains(identifier),
                  TimeZone(identifier: identifier) != nil else { continue }
            seen.insert(identifier)
            result.append(identifier)
        }
        return result
    }

    // IANA zone1970-style geographic choices; Foundation validation keeps the list Apple-recognized.
    private static let rawPrimaryIdentifiers = """
Europe/Andorra
Asia/Dubai
Asia/Kabul
Europe/Tirane
Asia/Yerevan
Antarctica/Casey
Antarctica/Davis
Antarctica/Mawson
Antarctica/Palmer
Antarctica/Rothera
Antarctica/Troll
Antarctica/Vostok
America/Argentina/Buenos_Aires
America/Argentina/Cordoba
America/Argentina/Salta
America/Argentina/Jujuy
America/Argentina/Tucuman
America/Argentina/Catamarca
America/Argentina/La_Rioja
America/Argentina/San_Juan
America/Argentina/Mendoza
America/Argentina/San_Luis
America/Argentina/Rio_Gallegos
America/Argentina/Ushuaia
Pacific/Pago_Pago
Europe/Vienna
Australia/Lord_Howe
Antarctica/Macquarie
Australia/Hobart
Australia/Melbourne
Australia/Sydney
Australia/Broken_Hill
Australia/Brisbane
Australia/Lindeman
Australia/Adelaide
Australia/Darwin
Australia/Perth
Australia/Eucla
Asia/Baku
America/Barbados
Asia/Dhaka
Europe/Brussels
Europe/Sofia
Atlantic/Bermuda
America/La_Paz
America/Noronha
America/Belem
America/Fortaleza
America/Recife
America/Araguaina
America/Maceio
America/Bahia
America/Sao_Paulo
America/Campo_Grande
America/Cuiaba
America/Santarem
America/Porto_Velho
America/Boa_Vista
America/Manaus
America/Eirunepe
America/Rio_Branco
Asia/Thimphu
Europe/Minsk
America/Belize
America/St_Johns
America/Halifax
America/Glace_Bay
America/Moncton
America/Goose_Bay
America/Toronto
America/Iqaluit
America/Winnipeg
America/Resolute
America/Rankin_Inlet
America/Regina
America/Swift_Current
America/Edmonton
America/Cambridge_Bay
America/Inuvik
America/Vancouver
America/Dawson_Creek
America/Fort_Nelson
America/Whitehorse
America/Dawson
Europe/Zurich
Africa/Abidjan
Pacific/Rarotonga
America/Santiago
America/Coyhaique
America/Punta_Arenas
Pacific/Easter
Asia/Shanghai
Asia/Urumqi
America/Bogota
America/Costa_Rica
America/Havana
Atlantic/Cape_Verde
Asia/Nicosia
Asia/Famagusta
Europe/Prague
Europe/Berlin
America/Santo_Domingo
Africa/Algiers
America/Guayaquil
Pacific/Galapagos
Europe/Tallinn
Africa/Cairo
Africa/El_Aaiun
Europe/Madrid
Africa/Ceuta
Atlantic/Canary
Europe/Helsinki
Pacific/Fiji
Atlantic/Stanley
Pacific/Kosrae
Atlantic/Faroe
Europe/Paris
Europe/London
Asia/Tbilisi
America/Cayenne
Europe/Gibraltar
America/Nuuk
America/Danmarkshavn
America/Scoresbysund
America/Thule
Europe/Athens
Atlantic/South_Georgia
America/Guatemala
Pacific/Guam
Africa/Bissau
America/Guyana
Asia/Hong_Kong
America/Tegucigalpa
America/Port-au-Prince
Europe/Budapest
Asia/Jakarta
Asia/Pontianak
Asia/Makassar
Asia/Jayapura
Europe/Dublin
Asia/Jerusalem
Asia/Kolkata
Indian/Chagos
Asia/Baghdad
Asia/Tehran
Europe/Rome
America/Jamaica
Asia/Amman
Asia/Tokyo
Africa/Nairobi
Asia/Bishkek
Pacific/Tarawa
Pacific/Kanton
Pacific/Kiritimati
Asia/Pyongyang
Asia/Seoul
Asia/Almaty
Asia/Qyzylorda
Asia/Qostanay
Asia/Aqtobe
Asia/Aqtau
Asia/Atyrau
Asia/Oral
Asia/Beirut
Asia/Colombo
Africa/Monrovia
Europe/Vilnius
Europe/Riga
Africa/Tripoli
Africa/Casablanca
Europe/Chisinau
Pacific/Kwajalein
Asia/Yangon
Asia/Ulaanbaatar
Asia/Hovd
Asia/Macau
America/Martinique
Europe/Malta
Indian/Mauritius
Indian/Maldives
America/Mexico_City
America/Cancun
America/Merida
America/Monterrey
America/Matamoros
America/Chihuahua
America/Ciudad_Juarez
America/Ojinaga
America/Mazatlan
America/Bahia_Banderas
America/Hermosillo
America/Tijuana
Asia/Kuching
Africa/Maputo
Africa/Windhoek
Pacific/Noumea
Pacific/Norfolk
Africa/Lagos
America/Managua
Asia/Kathmandu
Pacific/Nauru
Pacific/Niue
Pacific/Auckland
Pacific/Chatham
America/Panama
America/Lima
Pacific/Tahiti
Pacific/Marquesas
Pacific/Gambier
Pacific/Port_Moresby
Pacific/Bougainville
Asia/Manila
Asia/Karachi
Europe/Warsaw
America/Miquelon
Pacific/Pitcairn
America/Puerto_Rico
Asia/Gaza
Asia/Hebron
Europe/Lisbon
Atlantic/Madeira
Atlantic/Azores
Pacific/Palau
America/Asuncion
Asia/Qatar
Europe/Bucharest
Europe/Belgrade
Europe/Kaliningrad
Europe/Moscow
Europe/Simferopol
Europe/Kirov
Europe/Volgograd
Europe/Astrakhan
Europe/Saratov
Europe/Ulyanovsk
Europe/Samara
Asia/Yekaterinburg
Asia/Omsk
Asia/Novosibirsk
Asia/Barnaul
Asia/Tomsk
Asia/Novokuznetsk
Asia/Krasnoyarsk
Asia/Irkutsk
Asia/Chita
Asia/Yakutsk
Asia/Khandyga
Asia/Vladivostok
Asia/Ust-Nera
Asia/Magadan
Asia/Sakhalin
Asia/Srednekolymsk
Asia/Kamchatka
Asia/Anadyr
Asia/Riyadh
Pacific/Guadalcanal
Africa/Khartoum
Asia/Singapore
America/Paramaribo
Africa/Juba
Africa/Sao_Tome
America/El_Salvador
Asia/Damascus
America/Grand_Turk
Africa/Ndjamena
Asia/Bangkok
Asia/Dushanbe
Pacific/Fakaofo
Asia/Dili
Asia/Ashgabat
Africa/Tunis
Pacific/Tongatapu
Europe/Istanbul
Asia/Taipei
Europe/Kyiv
America/New_York
America/Detroit
America/Kentucky/Louisville
America/Kentucky/Monticello
America/Indiana/Indianapolis
America/Indiana/Vincennes
America/Indiana/Winamac
America/Indiana/Marengo
America/Indiana/Petersburg
America/Indiana/Vevay
America/Chicago
America/Indiana/Tell_City
America/Indiana/Knox
America/Menominee
America/North_Dakota/Center
America/North_Dakota/New_Salem
America/North_Dakota/Beulah
America/Denver
America/Boise
America/Phoenix
America/Los_Angeles
America/Anchorage
America/Juneau
America/Sitka
America/Metlakatla
America/Yakutat
America/Nome
America/Adak
Pacific/Honolulu
America/Montevideo
Asia/Samarkand
Asia/Tashkent
America/Caracas
Asia/Ho_Chi_Minh
Pacific/Efate
Pacific/Apia
Africa/Johannesburg
"""
}
